<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssessmentQuestionSeeder extends Seeder
{
    public function run(): void
    {
        // =====================================================================
        // CHAPTER 1 - ABOUT ME
        // =====================================================================
        $quiz1 = DB::table('assessments')->where('title', 'Quiz Chapter 1 - About Me')->first();
        if ($quiz1) {
            DB::table('assessment_questions')->where('assessment_id', $quiz1->id)->delete();
            DB::table('assessment_questions')->insert([
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'What greeting do we use in the morning?',
                    'option_a'       => 'Good night',
                    'option_b'       => 'Good evening',
                    'option_c'       => 'Good morning',
                    'option_d'       => 'Good afternoon',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'Which sentence is correct to introduce yourself?',
                    'option_a'       => 'I am name Galang.',
                    'option_b'       => 'My name is Galang.',
                    'option_c'       => 'Name my is Galang.',
                    'option_d'       => 'Is my name Galang.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'What is the correct response to "How are you?"',
                    'option_a'       => 'My name is Sinta.',
                    'option_b'       => 'I am from Bitung.',
                    'option_c'       => 'I am fine, thank you.',
                    'option_d'       => 'Nice to meet you.',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'Which word is used for a female friend?',
                    'option_a'       => 'He',
                    'option_b'       => 'His',
                    'option_c'       => 'Him',
                    'option_d'       => 'She',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'Fill in the blank: "I ___ a student at SMP Negeri 8 Bitung."',
                    'option_a'       => 'is',
                    'option_b'       => 'am',
                    'option_c'       => 'are',
                    'option_d'       => 'be',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'What does "diligent" mean in Indonesian?',
                    'option_a'       => 'Malas',
                    'option_b'       => 'Lucu',
                    'option_c'       => 'Rajin',
                    'option_d'       => 'Pemalu',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'Which is the correct farewell expression?',
                    'option_a'       => 'Good morning',
                    'option_b'       => 'How are you?',
                    'option_c'       => 'Nice to meet you',
                    'option_d'       => 'See you tomorrow',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => '"She ___ my best friend." What is the correct to be?',
                    'option_a'       => 'am',
                    'option_b'       => 'are',
                    'option_c'       => 'is',
                    'option_d'       => 'be',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'What does "hobby" mean in Indonesian?',
                    'option_a'       => 'Nama',
                    'option_b'       => 'Alamat',
                    'option_c'       => 'Umur',
                    'option_d'       => 'Hobi',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz1->id,
                    'question'       => 'Which sentence correctly introduces someone else?',
                    'option_a'       => 'I am Sinta.',
                    'option_b'       => 'This is my friend, Sinta.',
                    'option_c'       => 'Sinta am my friend.',
                    'option_d'       => 'My friend Sinta are kind.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
            ]);
        }

        // =====================================================================
        // CHAPTER 2 - CULINARY AND ME
        // =====================================================================
        $quiz2 = DB::table('assessments')->where('title', 'Quiz Chapter 2 - Culinary and Me')->first();
        if ($quiz2) {
            DB::table('assessment_questions')->where('assessment_id', $quiz2->id)->delete();
            DB::table('assessment_questions')->insert([
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'What does "sweet" mean in Indonesian?',
                    'option_a'       => 'Asin',
                    'option_b'       => 'Pahit',
                    'option_c'       => 'Manis',
                    'option_d'       => 'Asam',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'What is the texture of chips?',
                    'option_a'       => 'Soft',
                    'option_b'       => 'Crunchy',
                    'option_c'       => 'Smooth',
                    'option_d'       => 'Chewy',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'Which sentence is correct?',
                    'option_a'       => 'She cook rice every day.',
                    'option_b'       => 'She cooks rice every day.',
                    'option_c'       => 'She cooking rice every day.',
                    'option_d'       => 'She cooked rice every day.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'What does "sour" mean?',
                    'option_a'       => 'Manis',
                    'option_b'       => 'Pedas',
                    'option_c'       => 'Gurih',
                    'option_d'       => 'Asam',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => '"I ___ not like bitter food." What is the correct auxiliary verb?',
                    'option_a'       => 'does',
                    'option_b'       => 'do',
                    'option_c'       => 'did',
                    'option_d'       => 'is',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'What food is described as "nasi goreng" in English?',
                    'option_a'       => 'Steamed rice',
                    'option_b'       => 'Fried rice',
                    'option_c'       => 'Boiled rice',
                    'option_d'       => 'White rice',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'Which word means "menyiapkan" in English?',
                    'option_a'       => 'Eat',
                    'option_b'       => 'Drink',
                    'option_c'       => 'Cook',
                    'option_d'       => 'Buy',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'Which sentence expresses preference?',
                    'option_a'       => 'What is your name?',
                    'option_b'       => 'I love spicy food.',
                    'option_c'       => 'She is tall.',
                    'option_d'       => 'They are students.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => '"___ she drink milk every morning?" What is the correct auxiliary verb?',
                    'option_a'       => 'Do',
                    'option_b'       => 'Are',
                    'option_c'       => 'Does',
                    'option_d'       => 'Is',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz2->id,
                    'question'       => 'What is the meaning of "savory"?',
                    'option_a'       => 'Manis',
                    'option_b'       => 'Gurih',
                    'option_c'       => 'Asam',
                    'option_d'       => 'Pahit',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
            ]);
        }

        // =====================================================================
        // CHAPTER 3 - HOME SWEET HOME
        // =====================================================================
        $quiz3 = DB::table('assessments')->where('title', 'Quiz Chapter 3 - Home Sweet Home')->first();
        if ($quiz3) {
            DB::table('assessment_questions')->where('assessment_id', $quiz3->id)->delete();
            DB::table('assessment_questions')->insert([
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What room do we use for cooking?',
                    'option_a'       => 'Bedroom',
                    'option_b'       => 'Bathroom',
                    'option_c'       => 'Kitchen',
                    'option_d'       => 'Living room',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => '"There ___ a sofa in the living room." What is the correct verb?',
                    'option_a'       => 'are',
                    'option_b'       => 'is',
                    'option_c'       => 'am',
                    'option_d'       => 'be',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What preposition means "di bawah"?',
                    'option_a'       => 'On',
                    'option_b'       => 'In',
                    'option_c'       => 'Behind',
                    'option_d'       => 'Under',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What is "lemari" in English?',
                    'option_a'       => 'Mirror',
                    'option_b'       => 'Wardrobe',
                    'option_c'       => 'Curtain',
                    'option_d'       => 'Carpet',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => '"There ___ three chairs in the kitchen." What is the correct verb?',
                    'option_a'       => 'is',
                    'option_b'       => 'am',
                    'option_c'       => 'are',
                    'option_d'       => 'be',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What does "sweep the floor" mean?',
                    'option_a'       => 'Mengepel lantai',
                    'option_b'       => 'Menyapu lantai',
                    'option_c'       => 'Mencuci piring',
                    'option_d'       => 'Merapikan tempat tidur',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'Which word means "di sebelah"?',
                    'option_a'       => 'Behind',
                    'option_b'       => 'In front of',
                    'option_c'       => 'Next to',
                    'option_d'       => 'Between',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What is "kulkas" in English?',
                    'option_a'       => 'Stove',
                    'option_b'       => 'Refrigerator',
                    'option_c'       => 'Sink',
                    'option_d'       => 'Oven',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => 'What household activity means "mencuci pakaian"?',
                    'option_a'       => 'Iron the clothes',
                    'option_b'       => 'Make the bed',
                    'option_c'       => 'Do the laundry',
                    'option_d'       => 'Water the plants',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz3->id,
                    'question'       => '"The books are ___ the shelf." What preposition fits?',
                    'option_a'       => 'under',
                    'option_b'       => 'on',
                    'option_c'       => 'behind',
                    'option_d'       => 'between',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
            ]);
        }

        // =====================================================================
        // CHAPTER 4 - MY SCHOOL ACTIVITIES
        // =====================================================================
        $quiz4 = DB::table('assessments')->where('title', 'Quiz Chapter 4 - My School Activities')->first();
        if ($quiz4) {
            DB::table('assessment_questions')->where('assessment_id', $quiz4->id)->delete();
            DB::table('assessment_questions')->insert([
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'What subject is "Pendidikan Jasmani" in English?',
                    'option_a'       => 'Art',
                    'option_b'       => 'Science',
                    'option_c'       => 'Physical Education',
                    'option_d'       => 'Mathematics',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'How do we say "07.30" in English?',
                    'option_a'       => 'Half past eight',
                    'option_b'       => 'Quarter to seven',
                    'option_c'       => 'Half past seven',
                    'option_d'       => 'Quarter past eight',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'Which adverb of frequency means "selalu"?',
                    'option_a'       => 'Sometimes',
                    'option_b'       => 'Never',
                    'option_c'       => 'Rarely',
                    'option_d'       => 'Always',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => '"She ___ always comes late." Is this sentence correct?',
                    'option_a'       => 'Yes, it is correct.',
                    'option_b'       => 'No, it should be: She always comes late.',
                    'option_c'       => 'No, it should be: Always she comes late.',
                    'option_d'       => 'No, it should be: She comes always late.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'What does "take notes" mean?',
                    'option_a'       => 'Membaca buku',
                    'option_b'       => 'Mencatat',
                    'option_c'       => 'Mengerjakan PR',
                    'option_d'       => 'Belajar kelompok',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'Which adverb of frequency means "jarang"?',
                    'option_a'       => 'Often',
                    'option_b'       => 'Usually',
                    'option_c'       => 'Rarely',
                    'option_d'       => 'Always',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'What is the English term for "kelas daring"?',
                    'option_a'       => 'Offline class',
                    'option_b'       => 'Online class',
                    'option_c'       => 'Face-to-face class',
                    'option_d'       => 'Study group',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'How do we say "07.45" in English?',
                    'option_a'       => 'Quarter past seven',
                    'option_b'       => 'Quarter to eight',
                    'option_c'       => 'Half past seven',
                    'option_d'       => 'Quarter to seven',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'Which is a good study habit?',
                    'option_a'       => 'Playing games all night',
                    'option_b'       => 'Never doing homework',
                    'option_c'       => 'Reviewing notes before exam',
                    'option_d'       => 'Skipping class',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz4->id,
                    'question'       => 'What subject is "Informatika" in English?',
                    'option_a'       => 'Science',
                    'option_b'       => 'Mathematics',
                    'option_c'       => 'Computer Science',
                    'option_d'       => 'Social Science',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
            ]);
        }

        // =====================================================================
        // CHAPTER 5 - THIS IS MY SCHOOL
        // =====================================================================
        $quiz5 = DB::table('assessments')->where('title', 'Quiz Chapter 5 - This is My School')->first();
        if ($quiz5) {
            DB::table('assessment_questions')->where('assessment_id', $quiz5->id)->delete();
            DB::table('assessment_questions')->insert([
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'What is "perpustakaan" in English?',
                    'option_a'       => 'Laboratory',
                    'option_b'       => 'Library',
                    'option_c'       => 'Canteen',
                    'option_d'       => 'Auditorium',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => '"You ___ not be late to school." What is the correct modal?',
                    'option_a'       => 'can',
                    'option_b'       => 'will',
                    'option_c'       => 'must',
                    'option_d'       => 'shall',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'Which extracurricular is a sport?',
                    'option_a'       => 'Choir',
                    'option_b'       => 'Drama club',
                    'option_c'       => 'Basketball',
                    'option_d'       => 'Batik making',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'What direction means "belok kiri"?',
                    'option_a'       => 'Go straight',
                    'option_b'       => 'Turn right',
                    'option_c'       => 'Turn left',
                    'option_d'       => 'Go back',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => '"You must ___ a school uniform." What verb fills the blank?',
                    'option_a'       => 'wearing',
                    'option_b'       => 'wore',
                    'option_c'       => 'wears',
                    'option_d'       => 'wear',
                    'correct_answer' => 'D',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'What is "lapangan olahraga" in English?',
                    'option_a'       => 'Basketball court',
                    'option_b'       => 'Sports field',
                    'option_c'       => 'Parking lot',
                    'option_d'       => 'Garden',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'What does "extracurricular" mean in Indonesian?',
                    'option_a'       => 'Mata pelajaran',
                    'option_b'       => 'Kegiatan ekstrakurikuler',
                    'option_c'       => 'Jadwal sekolah',
                    'option_d'       => 'Peraturan sekolah',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'Which sentence uses MUST NOT correctly?',
                    'option_a'       => 'You must not wear uniform.',
                    'option_b'       => 'You must not litter in school.',
                    'option_c'       => 'You must not study hard.',
                    'option_d'       => 'You must not come to school.',
                    'correct_answer' => 'B',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => 'What is "kantin sekolah" in English?',
                    'option_a'       => 'School library',
                    'option_b'       => 'School hall',
                    'option_c'       => 'School canteen',
                    'option_d'       => 'School laboratory',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
                [
                    'assessment_id'  => $quiz5->id,
                    'question'       => '"Excuse me, ___ is the library?" What question word fits?',
                    'option_a'       => 'what',
                    'option_b'       => 'who',
                    'option_c'       => 'where',
                    'option_d'       => 'when',
                    'correct_answer' => 'C',
                    'created_at'     => now(),
                    'updated_at'     => now(),
                ],
            ]);
        }
    }
}